pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('petmanagement_backend_rajalakshmi/petmanagement_backend_rajalakshmi') {
                    sh 'npm install'
                }
            }
        }


        stage('Run Backend Unit Tests') {
            steps {
                dir('petmanagement_backend_rajalakshmi/petmanagement_backend_rajalakshmi') {
                    sh 'npm test'
                }
            }
        }


    }

    post {
        success {
            echo '✅ Deployment Successful!'
        }
        failure {
            echo '❌ Pipeline Failed.'
        }
    }
}

